### PR TITLE
added definitions for Mongo metrics

### PR DESCRIPTION
**Pull request by kfalconer**
### Relevant information

Describe what you have done and any details that you think are relevant or that you might want to discuss with us. 

### Checklist

* [x] I've read the guidelines and understand the acceptance criteria.
* [ ] The value of the attribute marked as `identifier` will be unique and valid. 
* [x] I've confirmed that my entity type wasn't already defined. If it is I'm providing an
 explanation above.

### CODE REVIEW

**Comment by kfalconer** [comment]
> hi @kfalconer ! can you give us a bit more context on this?
> 
> This PR will create the types but how is the data going to be created & managed

I am not sure I understand the question. Do you mean source of the metrics? This is the coming from the [nri-mongo](https://github.com/newrelic/nri-mongodb) integration.

I followed the same pattern as the other Infrastructure based integrations by defining the types. But it wasn't clear on the examples how the data is actually synthesized since there was no examples of that.

**Comment by naxhh** [comment]
@kfalconer I see what you mean.

Let me run down this on the teams providing this integrations.

The thing is that Infra entities go to a different pipeline and they don't use synthesis (yet) so manual work needs to be done in order to create such entities.

In the future these will go through synthesis and the process of creating entities will be simpler

**Comment by naxhh** [comment]
@kfalconer bringing more info from the team!

The work to bring these entities into the platform is already prioritized on the team backlog.

So i'll close this PR and let them do the required work and create the types.

Thanks a lot for your contribution!

**Comment by kfalconer** [comment]
Thanks for the update

**Pull request closed without merging**
